
pipeline {
    agent any
    
    environment {
        DOCKER_HUB_CREDENTIALS = 'docker-hub-credentials'
        DOCKER_IMAGE_NAME = 'sivaprasad272/getting-started'
        DOCKER_IMAGE_TAG = "latest-${env.BUILD_NUMBER}"
        GIT_URL = 'https://github.com/sivaprasad272/getting-started.git'
        DOCKER_CONTAINER_NAME='TO-DO-APP'
    }
    
    stages {
         stage('Cloning Git Code') {
            steps {
                git url: "${GIT_URL}"
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', DOCKER_HUB_CREDENTIALS) {
                        sh "docker build -t ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG} $WORKSPACE/app"
                    }
                }
            }
        }
        
        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', DOCKER_HUB_CREDENTIALS) {
                        sh "docker push ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}"
                    }
                }
            }
        }
        stage('Clean Up Local Image') {
            steps {
                script {
                    sh "docker rmi ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}"
                }
            }
        }
        stage('pull Docker Image') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/' ) {
                        sh "docker pull ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}"
                    }
                }
            }
        }
        stage('run docker container') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/',) {
                        sh "docker run -dp 3000:3000 --name $DOCKER_CONTAINER_NAME ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG} "
                    }
                }
            }
        }  
        stage('remove container') {
            steps {
                script {
                    sh "docker rm -f  ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}"
                }
            }
        }
    }   
}
